console.log("Equality test:", "Bushra Ali" === "Bushra Ali");
console.log("Inequality test:", "Bushra Ali" !== "Maria Ali");
console.log("lower case test:", "BUSHRA ALI".toLowerCase() === "bushra ali");
console.log("Equality test:", 1000 === 1000);
console.log("Inequality test:", 10 !== 9);
console.log("Greater than test:", 1000 > 100);
console.log("less than test:", 10 < 100);
console.log("Greater than and equal to test:", 10 >= 10);
console.log("Greater than and equal to test:", 5 <= 100);
console.log("And operator test:", true && true);
console.log("or operator test:", true || true);
var bus = [1, 2, 3, 4, 5];
console.log("test number", bus.includes(1));
var bus1 = [1, 2, 3, 4, 5];
console.log("test number", !bus1.includes(6));
